#!/bin/sh
DIR=$(cd "$(dirname $0)";pwd)
DOCKER_HOME=/home/user
FAKE_HOME=$DIR

docker run -it --rm --network host -e HOME=$DOCKER_HOME -u $(id -u):$(id -g) \
  -w $PWD -v $PWD:$PWD \
  -v $FAKE_HOME:$DOCKER_HOME \
  myvim/vimd:ide $*
