#!/bin/sh
DIR=$(cd "$(dirname $0)";pwd)
DOCKER_HOME=/home/user
FAKE_HOME=$DIR/.home
if [ ! -d "$FAKE_HOME" ]; then
  mkdir -p $FAKE_HOME
fi

docker run -it --rm --network host -e HOME=$DOCKER_HOME -u $(id -u):$(id -g) \
  -w $PWD -v $PWD:$PWD \
  -v $DIR/.vim:$DOCKER_HOME/.vim \
  -v $DIR/.vim/vimrc:$DOCKER_HOME/.config/nvim/init.vim \
  -v $FAKE_HOME:$DOCKER_HOME \
  myvim/vimd:ide $*
